# Generated by Django 2.2.9 on 2022-03-09 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220309_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['pub_date'], 'verbose_name_plural': 'Сортировка по дате'},
        ),
    ]
