# Generated by Django 2.2.9 on 2022-03-09 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20220309_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date'], 'verbose_name_plural': 'Сортировка постов по убыванию даты'},
        ),
    ]
