# Generated by Django 2.2.16 on 2022-04-13 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20220413_1545'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
